"""Add host_token to HostApproval table

Revision ID: 299a813b94db
Revises: 36b13f6f9d87
Create Date: 2025-09-17 16:37:18.660307

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "299a813b94db"
down_revision: Union[str, Sequence[str], None] = "36b13f6f9d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "host_approval", sa.Column("host_token", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_host_approval_host_token"),
        "host_approval",
        ["host_token"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_host_approval_host_token"), table_name="host_approval")
    op.drop_column("host_approval", "host_token")
    # ### end Alembic commands ###
