"""add_installation_request_tracking

Revision ID: 9ad14cccd903
Revises: 580e06d90203
Create Date: 2025-09-20 17:33:02.243154

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ad14cccd903"
down_revision: Union[str, Sequence[str], None] = "580e06d90203"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installation_request_tracking",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("packages_json", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("result_log", sa.Text(), nullable=True),
        sa.Column("success", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_installation_request_tracking_request_id"),
        "installation_request_tracking",
        ["request_id"],
        unique=True,
    )
    op.drop_index(
        op.f("ix_available_packages_collection_date"), table_name="available_packages"
    )
    op.drop_index(
        op.f("ix_available_packages_manager"), table_name="available_packages"
    )
    op.drop_index(op.f("ix_available_packages_name"), table_name="available_packages")
    op.drop_index(op.f("ix_available_packages_unique"), table_name="available_packages")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_available_packages_unique"),
        "available_packages",
        ["package_manager", "package_name"],
        unique=1,
    )
    op.create_index(
        op.f("ix_available_packages_name"),
        "available_packages",
        ["package_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_available_packages_manager"),
        "available_packages",
        ["package_manager"],
        unique=False,
    )
    op.create_index(
        op.f("ix_available_packages_collection_date"),
        "available_packages",
        ["collection_date"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_installation_request_tracking_request_id"),
        table_name="installation_request_tracking",
    )
    op.drop_table("installation_request_tracking")
    # ### end Alembic commands ###
