#!/usr/bin/env python3
# Copyright (c) 2024-2026 Bryan Everly
# Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
# See the LICENSE file in the project root for the full terms.

"""File-length gate: no tracked source file may exceed 1000 lines.

Windows counterpart to the POSIX ``lint-file-length`` recipe, whose ``bad=$(...)``
/ ``while read`` shell is not runnable by cmd.exe (make pins ``SHELL := cmd.exe``
on Windows).  Behaviour matches that recipe exactly: the same ``git ls-files``
globs, the same ``scripts/`` + ``*-i18n.ts`` exemptions, the same ``wc -l``
newline count, the same report format and exit status.

Pass explicit paths as arguments to check just those files (used by the tests);
with no arguments the tracked-file set comes from ``git ls-files``.
"""

import re
import subprocess  # nosec B404 - fixed argv (git ls-files), no shell
import sys
from pathlib import Path

MAX_LINES = 1000

PATTERNS = ["*.py", "*.pyx", "*.pxi", "*.ts", "*.tsx", "*.js", "*.jsx"]

# Documented, deliberate exemptions: scripts/ is utility code, and *-i18n.ts
# bundles are generated by gen_phase14_plugin_i18n.py (data, not code).
EXEMPT = re.compile(r"(^|/)scripts/|-i18n\.ts$")


def tracked_files() -> list:
    """Repo-relative paths of tracked source files, minus the exemptions."""
    result = subprocess.run(  # nosec B603 B607 - fixed argv, no shell
        ["git", "ls-files"] + PATTERNS,
        capture_output=True,
        text=True,
        check=True,
    )
    return [
        line for line in result.stdout.splitlines() if line and not EXEMPT.search(line)
    ]


def line_count(path: str) -> int:
    """Newlines in the file — what ``wc -l < file`` reports."""
    return Path(path).read_bytes().count(b"\n")


def offenders(paths) -> list:
    """(count, path) for each file over the limit, in the order given."""
    found = []
    for path in paths:
        try:
            count = line_count(path)
        except OSError:
            continue  # listed but unreadable (e.g. deleted since ls-files)
        if count > MAX_LINES:
            found.append((count, path))
    return found


def main(argv) -> int:
    if argv:
        paths = argv
    else:
        try:
            paths = tracked_files()
        except (OSError, subprocess.CalledProcessError) as exc:
            # A gate that cannot enumerate the files must not report success.
            print(f"ERROR: could not list tracked files: {exc}", file=sys.stderr)
            return 1
    over = offenders(paths)
    if over:
        print(f"ERROR: source files exceed the {MAX_LINES}-line limit:")
        for count, path in over:
            print(f"  {count:6d}  {path}")
        return 1
    print(f"[OK] all source files within {MAX_LINES} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
