#!/usr/bin/env python3
"""
OpenBSD PLIST Generator for sysmanage-agent
Automatically generates the package list (PLIST) file based on the source tree.
This ensures the PLIST stays in sync with the actual files in the repository.
"""

import os
import sys
from pathlib import Path


def generate_plist():
    """Generate PLIST file for OpenBSD port"""

    # Get repository root (two levels up from this script)
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent

    # Header with comments and directives
    plist_lines = [
        "@comment Auto-generated PLIST - DO NOT EDIT MANUALLY",
        "@comment Generated by: installer/openbsd/generate-plist.py",
        "@comment To regenerate: python3 installer/openbsd/generate-plist.py",
        "@comment",
        "@comment For official port submission, register these in /usr/ports/infrastructure/db/user.list",
        "@comment @newgroup _sysmanage:827",
        "@comment @newuser _sysmanage:827:_sysmanage::SysManage Agent:/nonexistent:/sbin/nologin",
        "@comment",
        "@comment rc.d script",
        "@rcscript ${RCDIR}/sysmanage_agent",
        "@comment",
        "@comment Application files",
        "libexec/sysmanage-agent/",
    ]

    # Add main.py
    plist_lines.append("libexec/sysmanage-agent/main.py")

    # Add alembic.ini if it exists
    if (repo_root / "alembic.ini").exists():
        plist_lines.append("libexec/sysmanage-agent/alembic.ini")

    # Add all source files
    plist_lines.append("libexec/sysmanage-agent/src/")

    # Collect all files in src/ directory
    src_files = []
    src_dir = repo_root / "src"

    if src_dir.exists():
        for root, dirs, files in os.walk(src_dir):
            # Exclude __pycache__ and other build artifacts
            dirs[:] = [
                d
                for d in dirs
                if d
                not in ["__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"]
            ]

            # Sort directories for consistent output
            dirs.sort()

            # Get relative path from src/
            rel_root = Path(root).relative_to(src_dir)

            # Add directory entries (for non-root dirs)
            if str(rel_root) != ".":
                dir_path = f"libexec/sysmanage-agent/src/{rel_root}/"
                if dir_path not in src_files:
                    src_files.append(dir_path)

            # Add file entries
            for file in sorted(files):
                if str(rel_root) == ".":
                    file_path = f"libexec/sysmanage-agent/src/{file}"
                else:
                    file_path = f"libexec/sysmanage-agent/src/{rel_root}/{file}"
                src_files.append(file_path)

    plist_lines.extend(src_files)

    # Add alembic directory if it exists
    alembic_dir = repo_root / "alembic"
    if alembic_dir.exists():
        plist_lines.append("libexec/sysmanage-agent/alembic/")

        alembic_files = []
        for root, dirs, files in os.walk(alembic_dir):
            dirs[:] = [
                d
                for d in dirs
                if d
                not in ["__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"]
            ]
            dirs.sort()
            rel_root = Path(root).relative_to(alembic_dir)

            if str(rel_root) != ".":
                dir_path = f"libexec/sysmanage-agent/alembic/{rel_root}/"
                if dir_path not in alembic_files:
                    alembic_files.append(dir_path)

            for file in sorted(files):
                if str(rel_root) == ".":
                    file_path = f"libexec/sysmanage-agent/alembic/{file}"
                else:
                    file_path = f"libexec/sysmanage-agent/alembic/{rel_root}/{file}"
                alembic_files.append(file_path)

        plist_lines.extend(alembic_files)

    # Add database directory if it exists
    database_dir = repo_root / "database"
    if database_dir.exists():
        plist_lines.append("libexec/sysmanage-agent/database/")

        database_files = []
        for root, dirs, files in os.walk(database_dir):
            dirs[:] = [
                d
                for d in dirs
                if d
                not in ["__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"]
            ]
            dirs.sort()
            rel_root = Path(root).relative_to(database_dir)

            if str(rel_root) != ".":
                dir_path = f"libexec/sysmanage-agent/database/{rel_root}/"
                if dir_path not in database_files:
                    database_files.append(dir_path)

            for file in sorted(files):
                if str(rel_root) == ".":
                    file_path = f"libexec/sysmanage-agent/database/{file}"
                else:
                    file_path = f"libexec/sysmanage-agent/database/{rel_root}/{file}"
                database_files.append(file_path)

        plist_lines.extend(database_files)

    # Add i18n directory if it exists
    i18n_dir = repo_root / "i18n"
    if i18n_dir.exists():
        plist_lines.append("libexec/sysmanage-agent/i18n/")

        i18n_files = []
        for root, dirs, files in os.walk(i18n_dir):
            dirs[:] = [
                d
                for d in dirs
                if d
                not in ["__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"]
            ]
            dirs.sort()
            rel_root = Path(root).relative_to(i18n_dir)

            if str(rel_root) != ".":
                dir_path = f"libexec/sysmanage-agent/i18n/{rel_root}/"
                if dir_path not in i18n_files:
                    i18n_files.append(dir_path)

            for file in sorted(files):
                if str(rel_root) == ".":
                    file_path = f"libexec/sysmanage-agent/i18n/{file}"
                else:
                    file_path = f"libexec/sysmanage-agent/i18n/{rel_root}/{file}"
                i18n_files.append(file_path)

        plist_lines.extend(i18n_files)

    # Add security directory if it exists
    security_dir = repo_root / "security"
    if security_dir.exists():
        plist_lines.append("libexec/sysmanage-agent/security/")

        security_files = []
        for root, dirs, files in os.walk(security_dir):
            dirs[:] = [
                d
                for d in dirs
                if d
                not in ["__pycache__", ".pytest_cache", ".mypy_cache", "node_modules"]
            ]
            dirs.sort()
            rel_root = Path(root).relative_to(security_dir)

            if str(rel_root) != ".":
                dir_path = f"libexec/sysmanage-agent/security/{rel_root}/"
                if dir_path not in security_files:
                    security_files.append(dir_path)

            for file in sorted(files):
                if str(rel_root) == ".":
                    file_path = f"libexec/sysmanage-agent/security/{file}"
                else:
                    file_path = f"libexec/sysmanage-agent/security/{rel_root}/{file}"
                security_files.append(file_path)

        plist_lines.extend(security_files)

    # Add share/examples
    plist_lines.extend(
        [
            "share/examples/sysmanage-agent/",
            "@sample ${SYSCONFDIR}/sysmanage-agent-system.yaml",
            "share/examples/sysmanage-agent/sysmanage-agent-system.yaml",
        ]
    )

    # Add share/doc
    plist_lines.extend(
        [
            "share/doc/sysmanage-agent/",
            "share/doc/sysmanage-agent/README.md",
        ]
    )

    # Add LICENSE if it exists
    if (repo_root / "LICENSE").exists():
        plist_lines.append("share/doc/sysmanage-agent/LICENSE")

    # Add SBOM if it exists
    sbom_dir = repo_root / "sbom"
    if sbom_dir.exists() and (sbom_dir / "sysmanage-agent-sbom.json").exists():
        plist_lines.extend(
            [
                "share/doc/sysmanage-agent/sbom/",
                "share/doc/sysmanage-agent/sbom/sysmanage-agent-sbom.json",
            ]
        )

    return plist_lines


def main():
    """Main function"""
    print("Generating OpenBSD PLIST...")

    # Get script directory
    script_dir = Path(__file__).parent
    plist_path = script_dir / "pkg" / "PLIST"

    # Generate PLIST
    plist_lines = generate_plist()

    # Write to file
    print(f"Writing PLIST to: {plist_path}")
    with open(plist_path, "w") as f:
        f.write("\n".join(plist_lines))
        f.write("\n")  # Final newline

    print(f"✓ Generated PLIST with {len(plist_lines)} entries")
    print(f"✓ PLIST written to: {plist_path}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
