"""
Debian preseed and script generators for VMM child host creation.

This module contains the preseed template and configuration generators used
for automated Debian installation on OpenBSD VMM.
"""


def generate_agent_config(
    hostname: str,
    port: int,
    use_https: bool,
    auto_approve_token: str = None,
) -> str:
    """
    Generate sysmanage-agent configuration file content.

    Args:
        hostname: SysManage server hostname
        port: SysManage server port
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Configuration file content as string
    """
    # Build auto_approve section if token provided
    auto_approve_section = ""
    if auto_approve_token:
        auto_approve_section = f"""
# Auto-approval token for automatic host approval
auto_approve:
  token: "{auto_approve_token}"
"""

    return f"""# sysmanage-agent configuration
# Auto-generated by VMM autoinstall for Debian Linux

# Server connection settings
server:
  hostname: "{hostname}"
  port: {port}
  use_https: {str(use_https).lower()}
  verify_ssl: false
{auto_approve_section}
# Client identification settings
client:
  registration_retry_interval: 30
  max_registration_retries: 10
  update_check_interval: 3600

# Internationalization settings
i18n:
  language: "en"

# Logging configuration
logging:
  level: "INFO|WARNING|ERROR|CRITICAL"
  file: "/var/log/sysmanage-agent/agent.log"
  format: "[%(asctime)s UTC] %(name)s - %(levelname)s - %(message)s"

# WebSocket connection settings
websocket:
  auto_reconnect: true
  reconnect_interval: 5
  ping_interval: 60

# Database configuration
database:
  path: "agent.db"
  auto_migrate: true

# Script execution configuration
script_execution:
  enabled: true
  timeout: 300
  max_concurrent: 3
  allowed_shells:
    - "sh"
    - "bash"
    - "dash"
  user_restrictions:
    allow_user_switching: false
    allowed_users: []
  security:
    restricted_paths:
      - "/etc/passwd"
      - "/etc/shadow"
      - "/etc/ssh/"
      - "/home/*/.ssh/"
      - "/root/.ssh/"
      - "*.key"
      - "*.pem"
    audit_logging: true
    require_approval: false
"""


def generate_preseed_file(  # pylint: disable=too-many-arguments,too-many-locals
    hostname: str,
    username: str,
    user_password_hash: str,
    root_password_hash: str,
    gateway_ip: str,
    vm_ip: str,
    dns_server: str = None,
    disk: str = "vda",
    timezone: str = "UTC",
    debian_version: str = "12",
    debian_codename: str = "bookworm",
    mirror_url: str = "deb.debian.org",
) -> str:
    """
    Generate Debian preseed file for automated installation.

    Args:
        hostname: VM hostname (FQDN)
        username: User to create
        user_password_hash: Pre-hashed password for the user (SHA-512)
        root_password_hash: Pre-hashed password for root (SHA-512)
        gateway_ip: Gateway IP address
        vm_ip: Static IP address for the VM
        dns_server: DNS server IP (defaults to gateway_ip)
        disk: Disk device to install to (default: vda for virtio)
        timezone: Timezone (default: UTC)
        debian_version: Debian version number (default: 12)
        debian_codename: Debian codename (default: bookworm)
        mirror_url: Debian mirror hostname (default: deb.debian.org)

    Returns:
        Preseed file content as string
    """
    if dns_server is None:
        dns_server = gateway_ip

    # Extract short hostname from FQDN
    short_hostname = hostname.split(".")[0]
    domain = ".".join(hostname.split(".")[1:]) if "." in hostname else "local"

    # Assume /24 subnet
    netmask = "255.255.255.0"  # NOSONAR - standard netmask for VM networking

    preseed = f"""# Debian {debian_version} ({debian_codename}) Preseed File
# Auto-generated by sysmanage VMM autoinstall
# For OpenBSD VMM/vmd virtualization

### Localization
d-i debian-installer/locale string en_US.UTF-8
d-i keyboard-configuration/xkb-keymap select us

### Network configuration
# Disable automatic network configuration (we use static IP)
d-i netcfg/choose_interface select auto
d-i netcfg/disable_autoconfig boolean true

# Static network configuration
d-i netcfg/get_ipaddress string {vm_ip}
d-i netcfg/get_netmask string {netmask}
d-i netcfg/get_gateway string {gateway_ip}
d-i netcfg/get_nameservers string {dns_server}
d-i netcfg/confirm_static boolean true

# Hostname and domain
d-i netcfg/get_hostname string {short_hostname}
d-i netcfg/get_domain string {domain}
d-i netcfg/hostname string {short_hostname}

### Mirror settings
d-i mirror/country string manual
d-i mirror/http/hostname string {mirror_url}
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string
d-i mirror/suite string {debian_codename}

### Account setup
# Root password (SHA-512 hash)
d-i passwd/root-login boolean true
d-i passwd/root-password-crypted password {root_password_hash}

# Create a normal user
d-i passwd/make-user boolean true
d-i passwd/user-fullname string {username}
d-i passwd/username string {username}
d-i passwd/user-password-crypted password {user_password_hash}
d-i passwd/user-default-groups string sudo

### Clock and time zone setup
d-i clock-setup/utc boolean true
d-i time/zone string {timezone}
d-i clock-setup/ntp boolean true

### Partitioning
# Use the virtio disk (vda in OpenBSD VMM)
d-i partman-auto/disk string /dev/{disk}
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic

# Confirm partitioning without asking
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

### Base system installation
d-i base-installer/install-recommends boolean false

### Apt setup
d-i apt-setup/non-free-firmware boolean true
d-i apt-setup/non-free boolean false
d-i apt-setup/contrib boolean false
d-i apt-setup/disable-cdrom-entries boolean true
d-i apt-setup/services-select multiselect security, updates
d-i apt-setup/security_host string security.debian.org

### Package selection
tasksel tasksel/first multiselect standard, ssh-server
d-i pkgsel/include string openssh-server sudo curl wget ca-certificates python3 python3-pip python3-venv
d-i pkgsel/upgrade select full-upgrade
d-i pkgsel/update-policy select unattended-upgrades

# Disable popularity contest
popularity-contest popularity-contest/participate boolean false

### Boot loader installation
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean false
d-i grub-installer/bootdev string /dev/{disk}

# Configure GRUB for serial console (critical for OpenBSD VMM)
d-i debian-installer/add-kernel-opts string console=ttyS0,115200n8

### Finishing up the installation
# Power off instead of reboot - VMM host will restart VM without ISO
d-i debian-installer/exit/halt boolean true
d-i debian-installer/exit/poweroff boolean true

### Late command - setup firstboot for sysmanage-agent
# Use setsid to fully detach poweroff - prevents installer from waiting
# 120 seconds allows finishing phase to complete before auto-poweroff
d-i preseed/late_command string \\
    mkdir -p /target/etc/sysmanage-agent; \\
    mkdir -p /target/var/log/sysmanage-agent; \\
    mkdir -p /target/var/lib/sysmanage-agent; \\
    echo "{short_hostname}" > /target/etc/hostname; \\
    echo "127.0.0.1 localhost" > /target/etc/hosts; \\
    echo "{vm_ip} {hostname} {short_hostname}" >> /target/etc/hosts; \\
    in-target systemctl enable sysmanage-firstboot.service || true; \\
    setsid sh -c "sleep 120; /sbin/poweroff -f" >/dev/null 2>&1 &
"""
    return preseed


def generate_firstboot_script(
    debian_version: str = "12",
    server_hostname: str = None,
    server_port: int = None,
    use_https: bool = False,
    auto_approve_token: str = None,
) -> str:
    """
    Generate first-boot script for Debian Linux.

    This script runs on first boot via systemd and installs
    the sysmanage-agent and its Python dependencies.

    Args:
        debian_version: Debian version number (default: 12)
        server_hostname: SysManage server hostname (for config generation)
        server_port: SysManage server port (for config generation)
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Script content as string
    """
    # Build config writing commands if server info is provided
    config_write_cmds = ""
    if server_hostname and server_port:
        use_https_str = "true" if use_https else "false"
        auto_approve_section = ""
        if auto_approve_token:
            auto_approve_section = f"""
echo '' >> /etc/sysmanage-agent.yaml
echo '# Auto-approval token for automatic host approval' >> /etc/sysmanage-agent.yaml
echo 'auto_approve:' >> /etc/sysmanage-agent.yaml
echo '  token: \"{auto_approve_token}\"' >> /etc/sysmanage-agent.yaml"""

        config_write_cmds = f"""
# Write the correct sysmanage-agent config (overwrites default from .deb)
echo "==> Writing sysmanage-agent configuration..."
echo '# sysmanage-agent configuration' > /etc/sysmanage-agent.yaml
echo '# Auto-generated by VMM autoinstall for Debian Linux' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Server connection settings' >> /etc/sysmanage-agent.yaml
echo 'server:' >> /etc/sysmanage-agent.yaml
echo '  hostname: \"{server_hostname}\"' >> /etc/sysmanage-agent.yaml
echo '  port: {server_port}' >> /etc/sysmanage-agent.yaml
echo '  use_https: {use_https_str}' >> /etc/sysmanage-agent.yaml
echo '  verify_ssl: false' >> /etc/sysmanage-agent.yaml
{auto_approve_section}
echo '' >> /etc/sysmanage-agent.yaml
echo '# Client identification settings' >> /etc/sysmanage-agent.yaml
echo 'client:' >> /etc/sysmanage-agent.yaml
echo '  registration_retry_interval: 30' >> /etc/sysmanage-agent.yaml
echo '  max_registration_retries: 10' >> /etc/sysmanage-agent.yaml
echo '  update_check_interval: 3600' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Internationalization settings' >> /etc/sysmanage-agent.yaml
echo 'i18n:' >> /etc/sysmanage-agent.yaml
echo '  language: \"en\"' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Logging configuration' >> /etc/sysmanage-agent.yaml
echo 'logging:' >> /etc/sysmanage-agent.yaml
echo '  level: \"INFO|WARNING|ERROR|CRITICAL\"' >> /etc/sysmanage-agent.yaml
echo '  file: \"/var/log/sysmanage-agent/agent.log\"' >> /etc/sysmanage-agent.yaml
echo '  format: \"[%%(asctime)s UTC] %%(name)s - %%(levelname)s - %%(message)s\"' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# WebSocket connection settings' >> /etc/sysmanage-agent.yaml
echo 'websocket:' >> /etc/sysmanage-agent.yaml
echo '  auto_reconnect: true' >> /etc/sysmanage-agent.yaml
echo '  reconnect_interval: 5' >> /etc/sysmanage-agent.yaml
echo '  ping_interval: 60' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Database configuration' >> /etc/sysmanage-agent.yaml
echo 'database:' >> /etc/sysmanage-agent.yaml
echo '  path: \"agent.db\"' >> /etc/sysmanage-agent.yaml
echo '  auto_migrate: true' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Script execution configuration' >> /etc/sysmanage-agent.yaml
echo 'script_execution:' >> /etc/sysmanage-agent.yaml
echo '  enabled: true' >> /etc/sysmanage-agent.yaml
echo '  timeout: 300' >> /etc/sysmanage-agent.yaml
echo '  max_concurrent: 3' >> /etc/sysmanage-agent.yaml
echo '  allowed_shells:' >> /etc/sysmanage-agent.yaml
echo '    - \"sh\"' >> /etc/sysmanage-agent.yaml
echo '    - \"bash\"' >> /etc/sysmanage-agent.yaml
echo '    - \"dash\"' >> /etc/sysmanage-agent.yaml
echo '  user_restrictions:' >> /etc/sysmanage-agent.yaml
echo '    allow_user_switching: false' >> /etc/sysmanage-agent.yaml
echo '    allowed_users: []' >> /etc/sysmanage-agent.yaml
echo '  security:' >> /etc/sysmanage-agent.yaml
echo '    restricted_paths:' >> /etc/sysmanage-agent.yaml
echo '      - \"/etc/passwd\"' >> /etc/sysmanage-agent.yaml
echo '      - \"/etc/shadow\"' >> /etc/sysmanage-agent.yaml
echo '      - \"/etc/ssh/\"' >> /etc/sysmanage-agent.yaml
echo '      - \"/home/*/.ssh/\"' >> /etc/sysmanage-agent.yaml
echo '      - \"/root/.ssh/\"' >> /etc/sysmanage-agent.yaml
echo '      - \"*.key\"' >> /etc/sysmanage-agent.yaml
echo '      - \"*.pem\"' >> /etc/sysmanage-agent.yaml
echo '    audit_logging: true' >> /etc/sysmanage-agent.yaml
echo '    require_approval: false' >> /etc/sysmanage-agent.yaml
echo "==> Configuration written successfully"
cat /etc/sysmanage-agent.yaml
"""

    return f"""#!/bin/bash
# First boot setup - install sysmanage-agent and dependencies
# This script runs on first boot via systemd oneshot service

set -e

# Log all output for debugging
LOGFILE="/var/log/sysmanage-firstboot.log"
exec >>"$LOGFILE" 2>&1

echo "==> First boot setup starting at $(date)"
echo "==> Debian version: {debian_version}"

# Wait for network to be ready
echo "==> Waiting for network..."
for i in $(seq 1 30); do
    if ping -c 1 deb.debian.org >/dev/null 2>&1; then
        echo "Network is ready"
        break
    fi
    echo "Waiting for network... attempt $i/30"
    sleep 2
done

# Update package index
echo "==> Updating package index..."
apt-get update

# Install Python dependencies from Debian repos
echo "==> Installing Python dependencies..."
DEBIAN_FRONTEND=noninteractive apt-get install -y \\
    python3 \\
    python3-pip \\
    python3-venv \\
    python3-websockets \\
    python3-yaml \\
    python3-aiohttp \\
    python3-cryptography \\
    python3-sqlalchemy \\
    python3-alembic \\
    python3-bcrypt \\
    python3-pydantic \\
    python3-cffi \\
    python3-greenlet \\
    python3-typing-extensions \\
    python3-mako \\
    python3-markupsafe \\
    python3-attr \\
    python3-multidict \\
    python3-yarl \\
    python3-frozenlist \\
    python3-aiosignal \\
    python3-idna \\
    python3-charset-normalizer

echo "==> Installed Python packages:"
dpkg -l | grep python3

# Install sysmanage-agent from the pre-downloaded package or GitHub
echo "==> Installing sysmanage-agent..."
if [ -f /root/sysmanage-agent.deb ]; then
    echo "Installing from local .deb package..."
    dpkg -i /root/sysmanage-agent.deb || apt-get install -f -y
    rm -f /root/sysmanage-agent.deb
elif [ -f /root/sysmanage_agent.whl ]; then
    echo "Installing from wheel package..."
    pip3 install --break-system-packages /root/sysmanage_agent.whl
    rm -f /root/sysmanage_agent.whl
else
    echo "Installing from GitHub releases..."
    # Get the latest release from GitHub
    LATEST_URL="https://api.github.com/repos/bceverly/sysmanage-agent/releases/latest"

    # Try to download Debian-specific package
    RELEASE_INFO=$(wget -qO- "$LATEST_URL" 2>/dev/null || curl -sL "$LATEST_URL" 2>/dev/null)
    if [ -n "$RELEASE_INFO" ]; then
        # Look for Debian package in release assets
        DEB_URL=$(echo "$RELEASE_INFO" | grep -oP '"browser_download_url":\\s*"\\K[^"]*debian{debian_version}[^"]*\\.deb' | head -1)
        if [ -n "$DEB_URL" ]; then
            echo "Downloading from: $DEB_URL"
            wget -O /tmp/sysmanage-agent.deb "$DEB_URL" && \\
                dpkg -i /tmp/sysmanage-agent.deb && \\
                rm -f /tmp/sysmanage-agent.deb || apt-get install -f -y
        else
            echo "No Debian package found, trying pip install..."
            pip3 install --break-system-packages sysmanage-agent || true
        fi
    else
        echo "Could not reach GitHub, trying pip install..."
        pip3 install --break-system-packages sysmanage-agent || true
    fi
fi

{config_write_cmds}
# Create systemd service for sysmanage-agent if not already present
echo "==> Creating systemd service..."
if [ ! -f /etc/systemd/system/sysmanage-agent.service ]; then
    cat > /etc/systemd/system/sysmanage-agent.service << 'SYSTEMD_SERVICE'
[Unit]
Description=SysManage Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 -m sysmanage_agent
WorkingDirectory=/var/lib/sysmanage-agent
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SYSTEMD_SERVICE
fi

# Reload systemd and enable service
echo "==> Enabling sysmanage-agent service..."
systemctl daemon-reload
systemctl enable sysmanage-agent

echo "==> Starting sysmanage-agent service..."
systemctl start sysmanage-agent

# Verify service status
sleep 3
systemctl status sysmanage-agent --no-pager || true

echo "==> First boot setup complete at $(date)"

# Disable this firstboot service so it doesn't run again
systemctl disable sysmanage-firstboot.service

# Clean up
rm -f /etc/systemd/system/sysmanage-firstboot.service
systemctl daemon-reload

echo "==> Firstboot service disabled and cleaned up"
"""


def generate_firstboot_systemd_service() -> str:  # pylint: disable=invalid-name
    """
    Generate systemd service unit for first-boot script.

    This oneshot service runs the firstboot script on the first boot
    after Debian installation completes.

    Returns:
        Systemd unit file content as string
    """
    return """[Unit]
Description=SysManage Agent First Boot Setup
After=network-online.target
Wants=network-online.target
ConditionPathExists=/root/sysmanage-firstboot.sh

[Service]
Type=oneshot
ExecStart=/bin/bash /root/sysmanage-firstboot.sh
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


def generate_grub_serial_config() -> str:
    """
    Generate GRUB configuration for serial console.

    This is appended to /etc/default/grub during late_command
    to ensure the installed system boots with serial console support.

    Returns:
        GRUB configuration snippet as string
    """
    return """# Serial console configuration for OpenBSD VMM
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,115200n8"
GRUB_CMDLINE_LINUX="console=ttyS0,115200n8"
"""
