"""
Ubuntu autoinstall and script generators for VMM child host creation.

This module contains the autoinstall YAML template and configuration generators
used for automated Ubuntu Server installation on OpenBSD VMM.

Key differences from Debian:
- Uses autoinstall YAML format instead of preseed
- Uses netplan for network configuration instead of /etc/network/interfaces
- Uses Subiquity installer instead of debian-installer
- Requires kernel ip= parameter for static IP during autoinstall
"""

import base64

from src.sysmanage_agent.operations.child_host_ubuntu_packages import (
    VMM_NETWORK_INTERFACE,
)


def generate_agent_config(
    hostname: str,
    port: int,
    use_https: bool,
    auto_approve_token: str = None,
) -> str:
    """
    Generate sysmanage-agent configuration file content.

    Args:
        hostname: SysManage server hostname
        port: SysManage server port
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Configuration file content as string
    """
    # Build auto_approve section if token provided
    auto_approve_section = ""
    if auto_approve_token:
        auto_approve_section = f"""
# Auto-approval token for automatic host approval
auto_approve:
  token: "{auto_approve_token}"
"""

    return f"""# sysmanage-agent configuration
# Auto-generated by VMM autoinstall for Ubuntu Linux

# Server connection settings
server:
  hostname: "{hostname}"
  port: {port}
  use_https: {str(use_https).lower()}
  verify_ssl: false
{auto_approve_section}
# Client identification settings
client:
  registration_retry_interval: 30
  max_registration_retries: 10
  update_check_interval: 3600

# Internationalization settings
i18n:
  language: "en"

# Logging configuration
logging:
  level: "INFO|WARNING|ERROR|CRITICAL"
  file: "/var/log/sysmanage-agent/agent.log"
  format: "[%(asctime)s UTC] %(name)s - %(levelname)s - %(message)s"

# WebSocket connection settings
websocket:
  auto_reconnect: true
  reconnect_interval: 5
  ping_interval: 60

# Database configuration
database:
  path: "agent.db"
  auto_migrate: true

# Script execution configuration
script_execution:
  enabled: true
  timeout: 300
  max_concurrent: 3
  allowed_shells:
    - "sh"
    - "bash"
    - "dash"
  user_restrictions:
    allow_user_switching: false
    allowed_users: []
  security:
    restricted_paths:
      - "/etc/passwd"
      - "/etc/shadow"
      - "/etc/ssh/"
      - "/home/*/.ssh/"
      - "/root/.ssh/"
      - "*.key"
      - "*.pem"
    audit_logging: true
    require_approval: false
"""


def generate_autoinstall_file(  # pylint: disable=too-many-arguments,too-many-locals
    hostname: str,
    username: str,
    password_hash: str,
    gateway_ip: str,
    vm_ip: str,
    dns_server: str,
    ubuntu_version: str = "24.04",  # NOSONAR pylint: disable=unused-argument # reserved for future use
    timezone: str = "UTC",
    shutdown_action: str = "poweroff",
) -> str:
    """
    Generate Ubuntu autoinstall YAML file for automated installation.

    Args:
        hostname: VM hostname (FQDN)
        username: User to create
        password_hash: Pre-hashed password for the user (SHA-512 $6$ format)
        gateway_ip: Gateway IP address
        vm_ip: Static IP address for the VM
        dns_server: DNS server IP (must be actual DNS, not gateway!)
        ubuntu_version: Ubuntu version number (default: 24.04)
        timezone: Timezone (default: UTC)
        shutdown_action: Action after install - "poweroff" or "reboot" (default: poweroff)

    Returns:
        Autoinstall YAML content as string
    """
    # Extract short hostname from FQDN
    short_hostname = hostname.split(".")[0]
    domain = ".".join(hostname.split(".")[1:]) if "." in hostname else "local"
    fqdn = f"{short_hostname}.{domain}"

    # Network interface name on OpenBSD VMM (virtio)
    interface = VMM_NETWORK_INTERFACE

    autoinstall = f"""#cloud-config
autoinstall:
  version: 1
  interactive-sections: []
  locale: en_US.UTF-8
  keyboard:
    layout: us
  timezone: {timezone}
  identity:
    hostname: {fqdn}
    username: {username}
    password: "{password_hash}"
  network:
    version: 2
    ethernets:
      {interface}:
        addresses:
          - {vm_ip}/24
        routes:
          - to: default
            via: {gateway_ip}
        nameservers:
          addresses:
            - {dns_server}

  # Storage configuration
  # 'direct' layout uses the whole disk without LVM
  storage:
    layout:
      name: direct

  # SSH configuration
  ssh:
    install-server: true
    allow-pw: true

  # Packages to install during autoinstall
  packages:
    - openssh-server
    - sudo
    - python3
    - python3-pip
    - python3-venv
    - curl
    - wget
    - ca-certificates

  # Late commands run at the end of installation
  # Use 'curtin in-target --' to run commands in the installed system
  late-commands:
    # Set up /etc/hosts with FQDN
    - curtin in-target -- /bin/bash -c "echo '{vm_ip} {fqdn} {short_hostname}' >> /etc/hosts"

    # Ensure serial console getty is enabled for OpenBSD VMM
    - curtin in-target -- systemctl enable serial-getty@ttyS0.service

    # Configure GRUB for serial console (persistent after install)
    - curtin in-target -- /bin/bash -c "sed -i 's/GRUB_CMDLINE_LINUX=\\"\\"/GRUB_CMDLINE_LINUX=\\"console=ttyS0,115200n8\\"/' /etc/default/grub"
    - curtin in-target -- update-grub

    # Create sysmanage-agent directories
    - curtin in-target -- mkdir -p /etc/sysmanage-agent
    - curtin in-target -- mkdir -p /var/log/sysmanage-agent
    - curtin in-target -- mkdir -p /var/lib/sysmanage-agent

  # Power off after install (VMM host will restart without ISO)
  shutdown: {shutdown_action}
"""
    return autoinstall


def generate_autoinstall_with_agent(  # pylint: disable=too-many-arguments,too-many-locals
    hostname: str,
    username: str,
    password_hash: str,
    gateway_ip: str,
    vm_ip: str,
    dns_server: str,
    server_hostname: str,
    server_port: int,
    use_https: bool,
    auto_approve_token: str = None,
    ubuntu_version: str = "24.04",
    timezone: str = "UTC",
    agent_deb_url: str = None,
) -> str:
    """
    Generate Ubuntu autoinstall YAML with sysmanage-agent setup.

    This creates a complete autoinstall file that includes all necessary
    late-commands to set up sysmanage-agent without needing external files.

    Args:
        hostname: VM hostname (FQDN)
        username: User to create
        password_hash: Pre-hashed password for the user (SHA-512 $6$ format)
        gateway_ip: Gateway IP address
        vm_ip: Static IP address for the VM
        dns_server: DNS server IP (must be actual DNS, not gateway!)
        server_hostname: SysManage server hostname
        server_port: SysManage server port
        use_https: Whether to use HTTPS
        auto_approve_token: Optional auto-approval token
        ubuntu_version: Ubuntu version number (default: 24.04)
        timezone: Timezone (default: UTC)
        agent_deb_url: Optional URL to download agent .deb from httpd

    Returns:
        Autoinstall YAML content as string
    """
    # Extract short hostname from FQDN
    short_hostname = hostname.split(".")[0]
    domain = ".".join(hostname.split(".")[1:]) if "." in hostname else "local"
    fqdn = f"{short_hostname}.{domain}"

    # Network interface name on OpenBSD VMM (virtio)
    interface = VMM_NETWORK_INTERFACE

    # Generate agent config content
    agent_config = generate_agent_config(
        hostname=server_hostname,
        port=server_port,
        use_https=use_https,
        auto_approve_token=auto_approve_token,
    )

    # Generate firstboot script content
    firstboot_script = generate_firstboot_script(
        ubuntu_version=ubuntu_version,
        server_hostname=server_hostname,
        server_port=server_port,
        use_https=use_https,
        auto_approve_token=auto_approve_token,
    )

    # Escape the content for embedding in YAML
    # We'll write these to temp files and base64 encode for safety
    config_b64 = base64.b64encode(agent_config.encode()).decode()
    firstboot_b64 = base64.b64encode(firstboot_script.encode()).decode()

    # Also base64 encode the systemd service file to avoid YAML parsing issues
    # (YAML interprets [Unit] as a list, breaking the heredoc approach)
    systemd_service = generate_firstboot_systemd_service()
    systemd_b64 = base64.b64encode(systemd_service.encode()).decode()

    # Build agent download command if URL provided
    agent_download_cmd = ""
    if agent_deb_url:
        agent_download_cmd = f"""
    # Download agent .deb from parent host
    - curtin in-target -- wget -q -O /root/sysmanage-agent.deb '{agent_deb_url}' || true"""

    autoinstall = f"""#cloud-config
autoinstall:
  version: 1
  interactive-sections: []
  locale: en_US.UTF-8
  keyboard:
    layout: us
  timezone: {timezone}
  identity:
    hostname: {fqdn}
    username: {username}
    password: "{password_hash}"
  network:
    version: 2
    ethernets:
      {interface}:
        addresses:
          - {vm_ip}/24
        routes:
          - to: default
            via: {gateway_ip}
        nameservers:
          addresses:
            - {dns_server}
  storage:
    layout:
      name: direct
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - openssh-server
    - sudo
    - python3
    - python3-pip
    - python3-venv
    - curl
    - wget
    - ca-certificates
  late-commands:
    - curtin in-target -- /bin/bash -c "echo '{vm_ip} {fqdn} {short_hostname}' >> /etc/hosts"
    - curtin in-target -- systemctl enable serial-getty@ttyS0.service
    - curtin in-target -- /bin/bash -c "sed -i 's/GRUB_CMDLINE_LINUX=\\"\\"/GRUB_CMDLINE_LINUX=\\"console=ttyS0,115200n8\\"/' /etc/default/grub"
    - curtin in-target -- update-grub
    - curtin in-target -- mkdir -p /etc/sysmanage-agent
    - curtin in-target -- mkdir -p /var/log/sysmanage-agent
    - curtin in-target -- mkdir -p /var/lib/sysmanage-agent
    - curtin in-target -- /bin/bash -c "echo '{config_b64}' | base64 -d > /etc/sysmanage-agent.yaml"
    - curtin in-target -- /bin/bash -c "echo '{firstboot_b64}' | base64 -d > /root/sysmanage-firstboot.sh"
    - curtin in-target -- chmod 755 /root/sysmanage-firstboot.sh
    - curtin in-target -- /bin/bash -c "echo '{systemd_b64}' | base64 -d > /etc/systemd/system/sysmanage-firstboot.service"
    - curtin in-target -- systemctl enable sysmanage-firstboot.service{agent_download_cmd}
  shutdown: poweroff
"""
    return autoinstall


def generate_firstboot_script(
    ubuntu_version: str = "24.04",
    server_hostname: str = None,
    server_port: int = None,
    use_https: bool = False,
    auto_approve_token: str = None,
) -> str:
    """
    Generate first-boot script for Ubuntu Linux.

    This script runs on first boot via systemd and installs
    the sysmanage-agent and its Python dependencies.

    Args:
        ubuntu_version: Ubuntu version number (default: 24.04)
        server_hostname: SysManage server hostname (for config generation)
        server_port: SysManage server port (for config generation)
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Script content as string
    """
    # Build config writing commands if server info is provided
    config_write_cmds = ""
    if server_hostname and server_port:
        use_https_str = "true" if use_https else "false"
        auto_approve_section = ""
        if auto_approve_token:
            auto_approve_section = f"""
echo '' >> /etc/sysmanage-agent.yaml
echo '# Auto-approval token for automatic host approval' >> /etc/sysmanage-agent.yaml
echo 'auto_approve:' >> /etc/sysmanage-agent.yaml
echo '  token: "{auto_approve_token}"' >> /etc/sysmanage-agent.yaml"""

        config_write_cmds = f"""
# Write the correct sysmanage-agent config (overwrites default from .deb)
echo "==> Writing sysmanage-agent configuration..."
echo '# sysmanage-agent configuration' > /etc/sysmanage-agent.yaml
echo '# Auto-generated by VMM autoinstall for Ubuntu Linux' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Server connection settings' >> /etc/sysmanage-agent.yaml
echo 'server:' >> /etc/sysmanage-agent.yaml
echo '  hostname: "{server_hostname}"' >> /etc/sysmanage-agent.yaml
echo '  port: {server_port}' >> /etc/sysmanage-agent.yaml
echo '  use_https: {use_https_str}' >> /etc/sysmanage-agent.yaml
echo '  verify_ssl: false' >> /etc/sysmanage-agent.yaml
{auto_approve_section}
echo '' >> /etc/sysmanage-agent.yaml
echo '# Client identification settings' >> /etc/sysmanage-agent.yaml
echo 'client:' >> /etc/sysmanage-agent.yaml
echo '  registration_retry_interval: 30' >> /etc/sysmanage-agent.yaml
echo '  max_registration_retries: 10' >> /etc/sysmanage-agent.yaml
echo '  update_check_interval: 3600' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Internationalization settings' >> /etc/sysmanage-agent.yaml
echo 'i18n:' >> /etc/sysmanage-agent.yaml
echo '  language: "en"' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Logging configuration' >> /etc/sysmanage-agent.yaml
echo 'logging:' >> /etc/sysmanage-agent.yaml
echo '  level: "INFO|WARNING|ERROR|CRITICAL"' >> /etc/sysmanage-agent.yaml
echo '  file: "/var/log/sysmanage-agent/agent.log"' >> /etc/sysmanage-agent.yaml
echo '  format: "[%%(asctime)s UTC] %%(name)s - %%(levelname)s - %%(message)s"' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# WebSocket connection settings' >> /etc/sysmanage-agent.yaml
echo 'websocket:' >> /etc/sysmanage-agent.yaml
echo '  auto_reconnect: true' >> /etc/sysmanage-agent.yaml
echo '  reconnect_interval: 5' >> /etc/sysmanage-agent.yaml
echo '  ping_interval: 60' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Database configuration' >> /etc/sysmanage-agent.yaml
echo 'database:' >> /etc/sysmanage-agent.yaml
echo '  path: "agent.db"' >> /etc/sysmanage-agent.yaml
echo '  auto_migrate: true' >> /etc/sysmanage-agent.yaml
echo '' >> /etc/sysmanage-agent.yaml
echo '# Script execution configuration' >> /etc/sysmanage-agent.yaml
echo 'script_execution:' >> /etc/sysmanage-agent.yaml
echo '  enabled: true' >> /etc/sysmanage-agent.yaml
echo '  timeout: 300' >> /etc/sysmanage-agent.yaml
echo '  max_concurrent: 3' >> /etc/sysmanage-agent.yaml
echo '  allowed_shells:' >> /etc/sysmanage-agent.yaml
echo '    - "sh"' >> /etc/sysmanage-agent.yaml
echo '    - "bash"' >> /etc/sysmanage-agent.yaml
echo '    - "dash"' >> /etc/sysmanage-agent.yaml
echo '  user_restrictions:' >> /etc/sysmanage-agent.yaml
echo '    allow_user_switching: false' >> /etc/sysmanage-agent.yaml
echo '    allowed_users: []' >> /etc/sysmanage-agent.yaml
echo '  security:' >> /etc/sysmanage-agent.yaml
echo '    restricted_paths:' >> /etc/sysmanage-agent.yaml
echo '      - "/etc/passwd"' >> /etc/sysmanage-agent.yaml
echo '      - "/etc/shadow"' >> /etc/sysmanage-agent.yaml
echo '      - "/etc/ssh/"' >> /etc/sysmanage-agent.yaml
echo '      - "/home/*/.ssh/"' >> /etc/sysmanage-agent.yaml
echo '      - "/root/.ssh/"' >> /etc/sysmanage-agent.yaml
echo '      - "*.key"' >> /etc/sysmanage-agent.yaml
echo '      - "*.pem"' >> /etc/sysmanage-agent.yaml
echo '    audit_logging: true' >> /etc/sysmanage-agent.yaml
echo '    require_approval: false' >> /etc/sysmanage-agent.yaml
echo "==> Configuration written successfully"
cat /etc/sysmanage-agent.yaml
"""

    return f"""#!/bin/bash
# First boot setup - install sysmanage-agent and dependencies
# This script runs on first boot via systemd oneshot service
# Generated for Ubuntu {ubuntu_version}

set -e

# Log all output for debugging
LOGFILE="/var/log/sysmanage-firstboot.log"
exec >>"$LOGFILE" 2>&1

echo "==> First boot setup starting at $(date)"
echo "==> Ubuntu version: {ubuntu_version}"

# Wait for network to be ready
echo "==> Waiting for network..."
for i in $(seq 1 30); do
    if ping -c 1 archive.ubuntu.com >/dev/null 2>&1; then
        echo "Network is ready"
        break
    fi
    echo "Waiting for network... attempt $i/30"
    sleep 2
done

# Update package index
echo "==> Updating package index..."
apt-get update

# Install Python dependencies from Ubuntu repos
echo "==> Installing Python dependencies..."
DEBIAN_FRONTEND=noninteractive apt-get install -y \\
    python3 \\
    python3-pip \\
    python3-venv \\
    python3-websockets \\
    python3-yaml \\
    python3-aiohttp \\
    python3-cryptography \\
    python3-sqlalchemy \\
    python3-alembic \\
    python3-bcrypt \\
    python3-pydantic \\
    python3-cffi \\
    python3-greenlet \\
    python3-typing-extensions \\
    python3-mako \\
    python3-markupsafe \\
    python3-attr \\
    python3-multidict \\
    python3-yarl \\
    python3-frozenlist \\
    python3-aiosignal \\
    python3-idna \\
    python3-charset-normalizer

echo "==> Installed Python packages:"
dpkg -l | grep python3

# Install sysmanage-agent from pre-downloaded package or Launchpad PPA
echo "==> Installing sysmanage-agent..."
if [ -f /root/sysmanage-agent.deb ]; then
    echo "Installing from local .deb package..."
    dpkg -i /root/sysmanage-agent.deb || apt-get install -f -y
    rm -f /root/sysmanage-agent.deb
elif [ -f /root/sysmanage_agent.whl ]; then
    echo "Installing from wheel package..."
    pip3 install --break-system-packages /root/sysmanage_agent.whl
    rm -f /root/sysmanage_agent.whl
else
    echo "Installing from Launchpad PPA..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common
    add-apt-repository -y ppa:bceverly/sysmanage-agent
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y sysmanage-agent
fi

{config_write_cmds}
# Create systemd service for sysmanage-agent only if not installed by .deb
# The .deb installs to /lib/systemd/system/, so check both locations
echo "==> Creating systemd service..."
if [ -f /lib/systemd/system/sysmanage-agent.service ]; then
    echo "Service file already installed by .deb package, skipping"
elif [ ! -f /etc/systemd/system/sysmanage-agent.service ]; then
    cat > /etc/systemd/system/sysmanage-agent.service << 'SYSTEMD_SERVICE'
[Unit]
Description=SysManage Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 -m sysmanage_agent
WorkingDirectory=/var/lib/sysmanage-agent
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SYSTEMD_SERVICE
fi

# Reload systemd and enable service
echo "==> Enabling sysmanage-agent service..."
systemctl daemon-reload
systemctl enable sysmanage-agent

echo "==> Starting sysmanage-agent service..."
systemctl start sysmanage-agent

# Verify service status
sleep 3
systemctl status sysmanage-agent --no-pager || true

echo "==> First boot setup complete at $(date)"

# Disable this firstboot service so it doesn't run again
systemctl disable sysmanage-firstboot.service

# Clean up
rm -f /etc/systemd/system/sysmanage-firstboot.service
rm -f /root/sysmanage-firstboot.sh
systemctl daemon-reload

echo "==> Firstboot service disabled and cleaned up"
"""


def generate_firstboot_systemd_service() -> str:  # pylint: disable=invalid-name
    """
    Generate systemd service unit for first-boot script.

    This oneshot service runs the firstboot script on the first boot
    after Ubuntu installation completes.

    Returns:
        Systemd unit file content as string
    """
    return """[Unit]
Description=SysManage Agent First Boot Setup
After=network-online.target
Wants=network-online.target
ConditionPathExists=/root/sysmanage-firstboot.sh

[Service]
Type=oneshot
ExecStart=/bin/bash /root/sysmanage-firstboot.sh
RemainAfterExit=yes
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


def generate_grub_serial_config() -> str:
    """
    Generate GRUB configuration for serial console.

    This is applied during late-commands to ensure the installed
    Ubuntu system boots with serial console support for OpenBSD VMM.

    Returns:
        GRUB configuration snippet as string
    """
    return """# Serial console configuration for OpenBSD VMM
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
GRUB_CMDLINE_LINUX_DEFAULT="console=ttyS0,115200n8"
GRUB_CMDLINE_LINUX="console=ttyS0,115200n8"
"""


def generate_kernel_boot_params(
    vm_ip: str,
    gateway_ip: str,
    hostname: str,
    interface: str = "enp0s2",
) -> str:
    """
    Generate kernel boot parameters for Ubuntu autoinstall with cidata ISO.

    Uses the cidata ISO approach where cloud-init auto-detects a filesystem
    labeled 'cidata' containing user-data and meta-data. This avoids the
    GRUB semicolon parsing issue with ds=nocloud-net;s=... parameters.

    The kernel ip= parameter is still needed for static networking since
    there's no DHCP on the VMM network.

    Args:
        vm_ip: Static IP address for the VM
        gateway_ip: Gateway IP address
        hostname: VM hostname (short name, not FQDN)
        interface: Network interface name (default: enp0s2 for OpenBSD VMM virtio)

    Returns:
        Kernel boot parameters string
    """
    # Kernel ip= parameter format:
    # ip=<client-ip>::<gateway>:<netmask>:<hostname>:<interface>:off
    ip_param = f"ip={vm_ip}::{gateway_ip}:255.255.255.0:{hostname}:{interface}:off"

    # With cidata ISO approach, cloud-init auto-detects the cidata-labeled
    # filesystem, so we don't need ds=nocloud-net;s=... parameter at all.
    # This avoids the GRUB semicolon parsing issue entirely.
    params = [
        "console=ttyS0,115200n8",
        "autoinstall",
        ip_param,
        "---",
    ]

    return " ".join(params)
