"""
OpenBSD site tarball script and config generators.

This module contains the script and configuration templates used
in the site tarball for VMM autoinstall.
"""


def generate_agent_config(
    hostname: str,
    port: int,
    use_https: bool,
    auto_approve_token: str = None,
) -> str:
    """
    Generate sysmanage-agent configuration file content.

    Args:
        hostname: SysManage server hostname
        port: SysManage server port
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Configuration file content as string
    """
    # Build auto_approve section if token provided
    auto_approve_section = ""
    if auto_approve_token:
        auto_approve_section = f"""
# Auto-approval token for automatic host approval
auto_approve:
  token: "{auto_approve_token}"
"""

    return f"""# sysmanage-agent configuration
# Auto-generated by VMM autoinstall

# Server connection settings
server:
  hostname: "{hostname}"
  port: {port}
  use_https: {str(use_https).lower()}
  verify_ssl: false
{auto_approve_section}
# Client identification settings
client:
  registration_retry_interval: 30
  max_registration_retries: 10
  update_check_interval: 3600

# Internationalization settings
i18n:
  language: "en"

# Logging configuration
logging:
  level: "INFO|WARNING|ERROR|CRITICAL"
  file: "/var/log/sysmanage-agent/agent.log"
  format: "[%(asctime)s UTC] %(name)s - %(levelname)s - %(message)s"

# WebSocket connection settings
websocket:
  auto_reconnect: true
  reconnect_interval: 5
  ping_interval: 60

# Database configuration
database:
  path: "agent.db"
  auto_migrate: true

# Script execution configuration
script_execution:
  enabled: true
  timeout: 300
  max_concurrent: 3
  allowed_shells:
    - "sh"
    - "ksh"
    - "csh"
  user_restrictions:
    allow_user_switching: false
    allowed_users: []
  security:
    restricted_paths:
      - "/etc/passwd"
      - "/etc/shadow"
      - "/etc/ssh/"
      - "/home/*/.ssh/"
      - "/root/.ssh/"
      - "*.key"
      - "*.pem"
    audit_logging: true
    require_approval: false
"""


def generate_firsttime_script() -> str:
    """
    Generate rc.firsttime script for first boot setup.

    This script runs on first boot and installs the sysmanage-agent
    and its Python dependencies from the packages included in the
    site tarball.

    Returns:
        Script content as string
    """
    return """#!/bin/sh
# First boot setup - install sysmanage-agent and dependencies

# Log all output for debugging (POSIX-compatible)
LOGFILE="/var/log/firsttime.log"
exec >>"$LOGFILE" 2>&1

echo "==> First boot setup starting at $(date)"

echo "==> Installing Python dependencies (offline)..."
PKG_COUNT=$(ls -1 /root/packages/*.tgz 2>/dev/null | wc -l)
echo "Found ${PKG_COUNT} packages in /root/packages/"

if [ ${PKG_COUNT} -gt 0 ]; then
    # Set PKG_PATH for all pkg_add operations
    export PKG_PATH="file:///root/packages/"

    # First install Python and its base dependencies
    # These have no Python package dependencies
    echo "==> Phase 1: Installing Python and base libraries..."
    for pkg in python sqlite3 gettext-runtime libiconv bzip2 libffi libb2 xz libcares gmp libyaml; do
        pkgfile=$(ls /root/packages/${pkg}-*.tgz 2>/dev/null | head -1)
        if [ -n "$pkgfile" ]; then
            echo "Installing: $pkgfile"
            pkg_add -D unsigned "$pkgfile" 2>&1 || echo "Warning: $pkgfile may have failed"
        fi
    done

    # Now install py3-* packages
    # Let pkg_add handle dependency resolution by installing them all at once
    echo "==> Phase 2: Installing Python packages..."
    py3_packages=$(ls /root/packages/py3-*.tgz 2>/dev/null)
    if [ -n "$py3_packages" ]; then
        echo "Installing all py3-* packages..."
        pkg_add -D unsigned /root/packages/py3-*.tgz 2>&1
        result=$?
        echo "pkg_add exit status: $result"
        if [ $result -ne 0 ]; then
            echo "Warning: Some py3-* packages may have failed to install"
            # Try installing them one by one for better error messages
            echo "==> Retrying py3-* packages individually..."
            for pkgfile in /root/packages/py3-*.tgz; do
                echo "Installing: $pkgfile"
                pkg_add -D unsigned "$pkgfile" 2>&1
            done
        fi
    fi

    echo "==> Installed packages:"
    pkg_info
fi

echo "==> Installing sysmanage-agent..."
AGENT_PKG=$(ls /root/sysmanage-agent-*.tgz 2>/dev/null | head -1)
if [ -n "$AGENT_PKG" ]; then
    echo "Agent package: $AGENT_PKG"
    export PKG_PATH="file:///root/packages/"
    pkg_add -D unsigned "$AGENT_PKG" 2>&1
    result=$?
    echo "Agent pkg_add exit status: $result"

    # Copy configuration (it's already in /etc from site tarball)
    if [ -f /etc/sysmanage-agent.yaml ]; then
        mkdir -p /etc/sysmanage-agent
        cp /etc/sysmanage-agent.yaml /etc/sysmanage-agent/
        echo "Copied configuration to /etc/sysmanage-agent/"
    fi

    # Enable and start service
    echo "Enabling sysmanage_agent service..."
    rcctl enable sysmanage_agent
    echo "Starting sysmanage_agent service..."
    rcctl start sysmanage_agent
    rcctl check sysmanage_agent
else
    echo "ERROR: No sysmanage-agent package found!"
fi

echo "==> Running syspatch..."
syspatch 2>&1

echo "==> Setup complete at $(date), shutting down..."
shutdown -p now
"""


def generate_install_site_script() -> str:
    """
    Generate install.site script (runs during installation).

    This script runs during the OpenBSD installation process,
    after the sets have been extracted but before first boot.

    Returns:
        Script content as string
    """
    return """#!/bin/sh
# Post-installation script - runs during install

# Fix installurl to use official mirror
echo "https://cdn.openbsd.org/pub/OpenBSD" > /etc/installurl

exit 0
"""
