"""
Alpine Linux site tarball script and config generators.

This module contains the script and configuration templates used
in the site tarball for Alpine Linux VMM autoinstall.
"""


def generate_agent_config(
    hostname: str,
    port: int,
    use_https: bool,
    auto_approve_token: str = None,
) -> str:
    """
    Generate sysmanage-agent configuration file content.

    Args:
        hostname: SysManage server hostname
        port: SysManage server port
        use_https: Whether to use HTTPS for server connection
        auto_approve_token: Optional UUID token for automatic host approval

    Returns:
        Configuration file content as string
    """
    # Build auto_approve section if token provided
    auto_approve_section = ""
    if auto_approve_token:
        auto_approve_section = f"""
# Auto-approval token for automatic host approval
auto_approve:
  token: "{auto_approve_token}"
"""

    return f"""# sysmanage-agent configuration
# Auto-generated by VMM autoinstall for Alpine Linux

# Server connection settings
server:
  hostname: "{hostname}"
  port: {port}
  use_https: {str(use_https).lower()}
  verify_ssl: false
{auto_approve_section}
# Client identification settings
client:
  registration_retry_interval: 30
  max_registration_retries: 10
  update_check_interval: 3600

# Internationalization settings
i18n:
  language: "en"

# Logging configuration
logging:
  level: "INFO|WARNING|ERROR|CRITICAL"
  file: "/var/log/sysmanage-agent/agent.log"
  format: "[%(asctime)s UTC] %(name)s - %(levelname)s - %(message)s"

# WebSocket connection settings
websocket:
  auto_reconnect: true
  reconnect_interval: 5
  ping_interval: 60

# Database configuration
database:
  path: "agent.db"
  auto_migrate: true

# Script execution configuration
script_execution:
  enabled: true
  timeout: 300
  max_concurrent: 3
  allowed_shells:
    - "sh"
    - "ash"
    - "bash"
  user_restrictions:
    allow_user_switching: false
    allowed_users: []
  security:
    restricted_paths:
      - "/etc/passwd"
      - "/etc/shadow"
      - "/etc/ssh/"
      - "/home/*/.ssh/"
      - "/root/.ssh/"
      - "*.key"
      - "*.pem"
    audit_logging: true
    require_approval: false
"""


def generate_firstboot_script() -> str:
    """
    Generate first-boot script for Alpine Linux.

    This script runs on first boot via /etc/local.d/ and installs
    the sysmanage-agent and its Python dependencies.

    Returns:
        Script content as string
    """
    return """#!/bin/sh
# First boot setup - install sysmanage-agent and dependencies
# This script runs on first boot via /etc/local.d/

# Log all output for debugging
LOGFILE="/var/log/sysmanage-firstboot.log"
exec >>"$LOGFILE" 2>&1

echo "==> First boot setup starting at $(date)"

# Enable community repository if not already enabled
echo "==> Ensuring community repository is enabled..."
if ! grep -q "community" /etc/apk/repositories; then
    ALPINE_VER=$(cat /etc/alpine-release | cut -d. -f1,2)
    echo "https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VER}/community" >> /etc/apk/repositories
fi

# Update package index
echo "==> Updating package index..."
apk update

# Install Python and dependencies from Alpine repos
echo "==> Installing Python dependencies..."
apk add --no-cache \
    python3 \
    py3-pip \
    py3-websockets \
    py3-yaml \
    py3-aiohttp \
    py3-cryptography \
    py3-sqlalchemy \
    py3-alembic \
    py3-bcrypt \
    py3-pydantic \
    py3-cffi \
    py3-greenlet \
    py3-typing-extensions \
    py3-mako \
    py3-markupsafe \
    py3-attrs \
    py3-multidict \
    py3-yarl \
    py3-frozenlist \
    py3-aiosignal \
    py3-idna \
    py3-charset-normalizer \
    py3-async-timeout

echo "==> Installed packages:"
apk info | grep py3

# Install sysmanage-agent from the pre-downloaded package
echo "==> Installing sysmanage-agent..."
if [ -f /root/sysmanage-agent.apk ]; then
    echo "Installing from local package..."
    apk add --allow-untrusted /root/sysmanage-agent.apk
    rm -f /root/sysmanage-agent.apk
elif [ -f /root/sysmanage_agent.whl ]; then
    echo "Installing from wheel package..."
    pip3 install --break-system-packages /root/sysmanage_agent.whl
    rm -f /root/sysmanage_agent.whl
else
    echo "Installing from GitHub releases..."
    # Get the latest release from GitHub
    LATEST_URL="https://api.github.com/repos/bceverly/sysmanage-agent/releases/latest"
    ALPINE_VER=$(cat /etc/alpine-release | cut -d. -f1,2 | tr -d '.')

    # Try to download Alpine-specific package
    RELEASE_INFO=$(wget -qO- "$LATEST_URL" 2>/dev/null || curl -sL "$LATEST_URL" 2>/dev/null)
    if [ -n "$RELEASE_INFO" ]; then
        # Look for Alpine package in release assets
        APK_URL=$(echo "$RELEASE_INFO" | grep -o "https://[^\"]*alpine${ALPINE_VER}\\.apk" | head -1)
        if [ -n "$APK_URL" ]; then
            echo "Downloading from: $APK_URL"
            wget -O /tmp/sysmanage-agent.apk "$APK_URL" && \
                apk add --allow-untrusted /tmp/sysmanage-agent.apk && \
                rm -f /tmp/sysmanage-agent.apk
        else
            echo "No Alpine package found, trying pip install..."
            pip3 install --break-system-packages sysmanage-agent
        fi
    else
        echo "Could not reach GitHub, trying pip install..."
        pip3 install --break-system-packages sysmanage-agent
    fi
fi

# Copy configuration (it should already be in /etc from site tarball)
echo "==> Configuring sysmanage-agent..."
if [ -f /etc/sysmanage-agent.yaml ]; then
    mkdir -p /etc/sysmanage-agent
    cp /etc/sysmanage-agent.yaml /etc/sysmanage-agent/
    echo "Copied configuration to /etc/sysmanage-agent/"
fi

# Create OpenRC init script for sysmanage-agent
echo "==> Creating OpenRC service..."
cat > /etc/init.d/sysmanage_agent << 'INITSCRIPT'
#!/sbin/openrc-run

name="sysmanage_agent"
description="SysManage Agent"

command="/usr/bin/python3"
command_args="-m sysmanage_agent"
command_background="yes"
pidfile="/run/${RC_SVCNAME}.pid"
directory="/var/lib/sysmanage-agent"

depend() {
    need net
    after firewall
}

start_pre() {
    checkpath --directory --mode 0750 /var/lib/sysmanage-agent
    checkpath --directory --mode 0750 /var/log/sysmanage-agent
}
INITSCRIPT
chmod 755 /etc/init.d/sysmanage_agent

# Enable and start service
echo "==> Enabling sysmanage_agent service..."
rc-update add sysmanage_agent default

echo "==> Starting sysmanage_agent service..."
rc-service sysmanage_agent start

# Verify service status
sleep 2
rc-service sysmanage_agent status

echo "==> First boot setup complete at $(date)"

# Remove this script so it doesn't run again
rm -f /etc/local.d/sysmanage-firstboot.start

# Optionally shutdown after first boot (like OpenBSD does)
# Uncomment the following line if you want the VM to shutdown after setup
# poweroff
"""


def generate_answer_file(
    hostname: str,
    username: str,
    user_password_hash: str,  # pylint: disable=unused-argument
    root_password_hash: str,  # pylint: disable=unused-argument
    gateway_ip: str,
    vm_ip: str,
    disk: str = "vda",
    timezone: str = "UTC",
) -> str:
    """
    Generate Alpine Linux setup-alpine answer file.

    This answer file is used by setup-alpine for automated installation.

    Args:
        hostname: VM hostname (FQDN)
        username: User to create
        user_password_hash: Pre-hashed password for the user (SHA-512)
        root_password_hash: Pre-hashed password for root (SHA-512)
        gateway_ip: Gateway IP address
        vm_ip: Static IP address for the VM
        disk: Disk device to install to (default: vda for virtio)
        timezone: Timezone (default: UTC)

    Returns:
        Answer file content as string
    """
    # Extract subnet from gateway IP for netmask calculation
    # Assume /24 subnet
    netmask = "255.255.255.0"

    # Get parent DNS - will be overridden at runtime
    dns = gateway_ip  # Use gateway as DNS, or could use 8.8.8.8

    # Alpine answer file format
    # See: https://docs.alpinelinux.org/user-handbook/0.1a/Installing/setup_alpine.html
    answer_file = f"""# Alpine Linux setup-alpine answer file
# Auto-generated by sysmanage VMM autoinstall

KEYMAPOPTS="us us"
HOSTNAMEOPTS="-n {hostname}"
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address {vm_ip}
    netmask {netmask}
    gateway {gateway_ip}
"
DNSOPTS="-d local -n {dns}"
TIMEZONEOPTS="-z {timezone}"
PROXYOPTS="none"
APKREPOSOPTS="-1"
USEROPTS="-a -g wheel {username}"
SSHDOPTS="-c openssh"
NTPOPTS="-c chrony"
DISKOPTS="-m sys /dev/{disk}"
LABORUOPTS="none"
"""
    return answer_file


def generate_overlay_script() -> str:
    """
    Generate script to create Alpine overlay/apkovl for automated install.

    This script runs on the installer to set up the overlay with
    sysmanage-agent configuration.

    Returns:
        Script content as string
    """
    return """#!/bin/sh
# Create Alpine overlay for sysmanage-agent configuration
# This script is run during installation

OVERLAY_DIR="/tmp/overlay"
mkdir -p "$OVERLAY_DIR"

# Copy pre-configured files
if [ -d /media/cdrom/overlay ]; then
    cp -a /media/cdrom/overlay/* "$OVERLAY_DIR/"
fi

# Create the apkovl tarball
cd "$OVERLAY_DIR"
tar czf /tmp/overlay.apkovl.tar.gz .

echo "Overlay created at /tmp/overlay.apkovl.tar.gz"
"""
