name: Build CentOS/RHEL/Fedora Package

on:
  # Trigger on version tags (e.g., v1.0.0, v2.1.3)
  push:
    tags:
      - 'v*.*.*'

  # Manual trigger with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed for creating releases

jobs:
  # Wait for CI tests to pass before building
  wait-for-tests:
    name: Wait for CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI workflow
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Backend Tests (Python 3.10)'  # Just check one of the matrix tests
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  build-rpm:
    name: Build .rpm Package
    runs-on: ubuntu-latest
    needs: wait-for-tests
    container:
      image: rockylinux:9

    steps:
      - name: Install git and dependencies
        run: |
          dnf install -y git python3 python3-pip python3-devel rpm-build rpmdevtools rsync tar gzip sed findutils

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Determine version
        id: version
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_VERSION: ${{ github.event.inputs.version }}
          REF: ${{ github.ref }}
        run: |
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            # Strip 'v' prefix if present in manual input
            VERSION="${INPUT_VERSION#v}"
          else
            # Extract version from tag (remove 'v' prefix)
            VERSION="${REF#refs/tags/v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Set up RPM build tree
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

          # Create source tarball
          TAR_NAME="sysmanage-agent-$VERSION"
          TAR_DIR="/tmp/$TAR_NAME"
          mkdir -p "$TAR_DIR"

          # Copy source files
          rsync -a --exclude='htmlcov' --exclude='__pycache__' --exclude='*.pyc' --exclude='.pytest_cache' \
            src/ "$TAR_DIR/src/"
          cp main.py "$TAR_DIR/"
          cp alembic.ini "$TAR_DIR/"
          cp requirements-prod.txt "$TAR_DIR/"
          cp README.md "$TAR_DIR/" || touch "$TAR_DIR/README.md"
          cp LICENSE "$TAR_DIR/" || touch "$TAR_DIR/LICENSE"

          # Copy installer files
          mkdir -p "$TAR_DIR/installer/centos"
          cp installer/centos/*.service "$TAR_DIR/installer/centos/"
          cp installer/centos/*.sudoers "$TAR_DIR/installer/centos/"
          cp installer/centos/*.example "$TAR_DIR/installer/centos/"
          cp installer/centos/sysmanage-agent.spec "$TAR_DIR/installer/centos/"

          # Create tarball
          cd /tmp
          tar czf ~/rpmbuild/SOURCES/sysmanage-agent-$VERSION.tar.gz "$TAR_NAME/"

          echo "Source tarball created"

      - name: Update spec file with version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          # Extract spec file from source tarball
          tar -xzf ~/rpmbuild/SOURCES/sysmanage-agent-$VERSION.tar.gz -C /tmp \
            sysmanage-agent-$VERSION/installer/centos/sysmanage-agent.spec
          cp /tmp/sysmanage-agent-$VERSION/installer/centos/sysmanage-agent.spec ~/rpmbuild/SPECS/

          DATE=$(date "+%a %b %d %Y")

          # Update version and changelog date
          sed -i "s/^Version:.*/Version:        $VERSION/" ~/rpmbuild/SPECS/sysmanage-agent.spec
          sed -i "s/^\\* Mon Oct 14 2024/\\* $DATE/" ~/rpmbuild/SPECS/sysmanage-agent.spec

          echo "Spec file updated to version $VERSION"

      - name: Build RPM package
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          rpmbuild -bb ~/rpmbuild/SPECS/sysmanage-agent.spec

          # Find the built RPM
          RPM_FILE=$(find ~/rpmbuild/RPMS -name "sysmanage-agent-$VERSION-*.rpm" | head -1)

          if [ -z "$RPM_FILE" ]; then
            echo "ERROR: RPM package not found!"
            exit 1
          fi

          # Copy to workspace
          cp "$RPM_FILE" "$GITHUB_WORKSPACE/"

          echo "RPM package built: $(basename $RPM_FILE)"

      - name: Generate package information
        id: package_info
        run: |
          RPM_FILE=$(ls sysmanage-agent_*.rpm 2>/dev/null || ls sysmanage-agent-*.rpm)
          echo "rpm_file=$RPM_FILE" >> $GITHUB_OUTPUT

          # Get package info
          rpm -qip "$RPM_FILE"
          rpm -qlp "$RPM_FILE"

          # Generate SHA256 checksum
          sha256sum "$RPM_FILE" > "$RPM_FILE.sha256"

          echo "Package built: $RPM_FILE"
          echo "Size: $(du -h "$RPM_FILE" | cut -f1)"

      - name: Upload .rpm as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysmanage-agent-rpm
          path: |
            sysmanage-agent*.rpm
            sysmanage-agent*.rpm.sha256

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            sysmanage-agent*.rpm
            sysmanage-agent*.rpm.sha256
          body: |
            # SysManage Agent v${{ steps.version.outputs.version }} - RPM Package

            ## Installation on CentOS/RHEL/Fedora/Rocky/AlmaLinux

            ```bash
            # Download the .rpm file
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ steps.package_info.outputs.rpm_file }}

            # Install the package
            sudo dnf install ./${{ steps.package_info.outputs.rpm_file }}
            # or
            sudo yum install ./${{ steps.package_info.outputs.rpm_file }}
            # or
            sudo rpm -ivh ./${{ steps.package_info.outputs.rpm_file }}

            # Configure the agent
            sudo nano /etc/sysmanage-agent.yaml

            # Restart the service
            sudo systemctl restart sysmanage-agent
            ```

            ## What's Included

            - System management agent service
            - Automatic startup with systemd
            - Sudoers configuration for system management (DNF/YUM, firewalld, SELinux)
            - Example configuration file

            ## Supported Platforms

            - CentOS Stream 9+
            - RHEL 9+
            - Fedora 38+
            - Rocky Linux 9+
            - AlmaLinux 9+

            ## Checksum Verification

            ```bash
            sha256sum -c ${{ steps.package_info.outputs.rpm_file }}.sha256
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update RPM repository in sysmanage-docs
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        env:
          DOCS_REPO_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
          RPM_FILE: ${{ steps.package_info.outputs.rpm_file }}
        run: |
          echo "=========================================="
          echo "Updating RPM Repository in sysmanage-docs"
          echo "=========================================="

          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone sysmanage-docs repository
          echo "📦 Cloning sysmanage-docs repository..."
          git clone https://x-access-token:${DOCS_REPO_TOKEN}@github.com/bceverly/sysmanage-docs.git /tmp/sysmanage-docs

          # Copy .rpm file to temporary location
          echo "📋 Copying .rpm file..."
          cp "$RPM_FILE" /tmp/

          # Determine target repository based on package name
          # Package name should be like: sysmanage-agent-1.0.0-1.el9.x86_64.rpm
          if echo "$RPM_FILE" | grep -q '.el9.'; then
            TARGET="el9"
            echo "📍 Target: EL9 (RHEL 9, Rocky 9, AlmaLinux 9, CentOS Stream 9)"
          elif echo "$RPM_FILE" | grep -q '.el8.'; then
            TARGET="el8"
            echo "📍 Target: EL8 (RHEL 8, Rocky 8, AlmaLinux 8)"
          elif echo "$RPM_FILE" | grep -q '.fc'; then
            TARGET="fedora/39"
            echo "📍 Target: Fedora 39+"
          else
            # Default to el9
            TARGET="el9"
            echo "⚠️  Could not determine target from package name, defaulting to EL9"
          fi

          # Run update-repo.sh script
          echo "🔄 Updating RPM repository..."
          cd /tmp/sysmanage-docs/repo/rpm
          chmod +x update-repo.sh
          ./update-repo.sh "/tmp/$RPM_FILE" "$TARGET"

          # Commit and push changes
          echo "💾 Committing changes..."
          cd /tmp/sysmanage-docs
          git add repo/
          git commit -m "Add sysmanage-agent version $VERSION to $TARGET RPM repository

          Automatically updated by GitHub Actions from sysmanage-agent release ${{ github.ref_name }}.

          - Package: $RPM_FILE
          - Target: $TARGET
          - Release: ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}"

          echo "🚀 Pushing to sysmanage-docs..."
          git push

          echo "✅ RPM repository updated successfully!"
          echo "📍 Changes will be live on GitHub Pages in 2-5 minutes"
          echo "🔗 Repository: https://bceverly.github.io/sysmanage-docs/repo/rpm/$TARGET/x86_64"
