name: Build FreeBSD Package

on:
  # Trigger on version tags (e.g., v1.0.0, v2.1.3)
  push:
    tags:
      - 'v*.*.*'

  # Manual trigger with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write  # Needed for creating releases

jobs:
  # Wait for CI tests to pass before building
  wait-for-tests:
    name: Wait for CI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI workflow
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'Backend Tests (Python 3.10)'  # Just check one of the matrix tests
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  build-pkg:
    name: Build .pkg Package
    runs-on: ubuntu-latest
    needs: wait-for-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Determine version
        id: version
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_VERSION: ${{ github.event.inputs.version }}
          REF: ${{ github.ref }}
        run: |
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            # Strip 'v' prefix if present in manual input
            VERSION="${INPUT_VERSION#v}"
          else
            # Extract version from tag (remove 'v' prefix)
            VERSION="${REF#refs/tags/v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Install FreeBSD package build tools
        run: |
          sudo apt-get update
          # Try to install FreeBSD pkg tools or alternatives
          # We may need to install libarchive-tools for tar/archive handling
          sudo apt-get install -y \
            libarchive-tools \
            python3-dev \
            python3-pip \
            python3-setuptools \
            build-essential \
            pkg-config \
            gzip \
            tar \
            xz-utils

      - name: Set up FreeBSD package structure
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Setting up FreeBSD package structure..."

          # Create build directories
          mkdir -p build/freebsd/package-root/usr/local/lib/sysmanage-agent
          mkdir -p build/freebsd/package-root/usr/local/etc/sysmanage-agent
          mkdir -p build/freebsd/package-root/usr/local/etc/rc.d
          mkdir -p build/freebsd/package-root/var/log/sysmanage-agent
          mkdir -p build/freebsd/package-root/var/run/sysmanage

          # Copy agent files
          cp -R src build/freebsd/package-root/usr/local/lib/sysmanage-agent/
          cp main.py build/freebsd/package-root/usr/local/lib/sysmanage-agent/
          cp requirements.txt build/freebsd/package-root/usr/local/lib/sysmanage-agent/
          cp alembic.ini build/freebsd/package-root/usr/local/lib/sysmanage-agent/

          # Copy configuration files
          cp installer/freebsd/config.yaml.example build/freebsd/package-root/usr/local/etc/sysmanage-agent/
          cp installer/freebsd/sysmanage-agent.rc build/freebsd/package-root/usr/local/etc/rc.d/sysmanage_agent
          cp installer/freebsd/sysmanage-agent-wrapper.sh build/freebsd/package-root/usr/local/lib/sysmanage-agent/

          # Set executable permissions
          chmod +x build/freebsd/package-root/usr/local/etc/rc.d/sysmanage_agent
          chmod +x build/freebsd/package-root/usr/local/lib/sysmanage-agent/sysmanage-agent-wrapper.sh

          # Update manifest with version
          sed "s/version: \".*\"/version: \"$VERSION\"/" installer/freebsd/+MANIFEST > build/freebsd/+MANIFEST

      - name: Create FreeBSD package using libarchive
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "Creating FreeBSD package..."
          cd build/freebsd

          # Create the package archive
          # FreeBSD packages are typically txz (tar.xz) files with specific structure
          # First create the manifest and metadata

          # Create package metadata files
          echo "+COMPACT_MANIFEST" > +COMPACT_MANIFEST

          # Create the package contents
          cd package-root
          find . -type f | sort > ../+CONTENTS

          # Create the final package file
          cd ..
          PKG_FILE="sysmanage-agent-$VERSION.pkg"

          # Create package archive (FreeBSD packages are .txz files)
          tar -cf - +COMPACT_MANIFEST +MANIFEST +CONTENTS package-root | xz -c > "../$PKG_FILE"

          # Move to dist directory
          mkdir -p ../../installer/dist
          mv "../$PKG_FILE" ../../installer/dist/

          echo "Package created: installer/dist/$PKG_FILE"

      - name: Generate package information
        id: package_info
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          PKG_FILE="sysmanage-agent-$VERSION.pkg"
          echo "pkg_file=$PKG_FILE" >> $GITHUB_OUTPUT

          # Generate SHA256 checksum
          cd installer/dist
          sha256sum "$PKG_FILE" > "$PKG_FILE.sha256"

          echo "Package built: $PKG_FILE"
          echo "Size: $(du -h "$PKG_FILE" | cut -f1)"

          # Show package contents
          echo "Package contents:"
          tar -tf "$PKG_FILE" | head -20

      - name: Upload .pkg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysmanage-agent-freebsd-pkg
          path: |
            installer/dist/sysmanage-agent-*.pkg
            installer/dist/sysmanage-agent-*.pkg.sha256

      - name: Create GitHub Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            installer/dist/sysmanage-agent-*.pkg
            installer/dist/sysmanage-agent-*.pkg.sha256
          body: |
            # SysManage Agent v${{ steps.version.outputs.version }}

            ## Installation on FreeBSD

            ```bash
            # Download the .pkg file
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/${{ steps.package_info.outputs.pkg_file }}

            # Install the package
            sudo pkg add ${{ steps.package_info.outputs.pkg_file }}

            # Configure the agent
            sudo nano /etc/sysmanage-agent.yaml

            # Enable and start the service
            sudo sysrc sysmanage_agent_enable=YES
            sudo service sysmanage_agent start
            ```

            ## What's Included

            - System management agent service
            - FreeBSD rc.d service script
            - Automatic user/group creation
            - Example configuration file
            - Certificate storage directory

            ## Supported Platforms

            - FreeBSD 13.x
            - FreeBSD 14.x

            ## Checksum Verification

            ```bash
            sha256sum -c ${{ steps.package_info.outputs.pkg_file }}.sha256
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}