name: Test Snap Strict Deploy

on:
  # Manual trigger with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to use (e.g., 1.0.0 or v1.0.0)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build-and-publish-snap-strict:
    name: Build and Publish Strict Snap
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: |
          # Strip 'v' prefix if present in manual input
          VERSION="${{ github.event.inputs.version }}"
          VERSION="${VERSION#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Create VERSION file
        run: |
          echo "${{ steps.version.outputs.version }}" > VERSION
          echo "VERSION file contents:"
          cat VERSION

      - name: Create source tarball for snap
        run: |
          echo "Creating clean source tarball..."
          tar czf installer/ubuntu-snap-strict/sysmanage-agent-src.tar.gz \
            --exclude='.venv' \
            --exclude='.git' \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.pytest_cache' \
            --exclude='agent.db' \
            src main.py alembic.ini VERSION
          echo "Tarball created successfully"
          ls -lh installer/ubuntu-snap-strict/sysmanage-agent-src.tar.gz

      - name: Build snap with snapcraft
        uses: snapcore/action-build@v1
        id: build_snap
        with:
          path: installer/ubuntu-snap-strict

      - name: List built snap
        run: |
          ls -lh installer/ubuntu-snap-strict/*.snap

      - name: Get snap filename
        id: snap_file
        run: |
          SNAP_FILE=$(ls installer/ubuntu-snap-strict/sysmanage-agent-strict_*.snap | head -1)
          echo "snap_file=$SNAP_FILE" >> $GITHUB_OUTPUT
          echo "Built snap: $SNAP_FILE"

      - name: Install snapcraft login credentials
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          mkdir -p ~/.local/share/snapcraft
          echo "$SNAPCRAFT_STORE_CREDENTIALS" > ~/.local/share/snapcraft/credentials.json
          snapcraft whoami

      - name: Upload snap to edge channel
        run: |
          snapcraft upload --release=edge ${{ steps.snap_file.outputs.snap_file }}

      - name: Get snap status
        run: |
          snapcraft status sysmanage-agent-strict

      - name: Print completion message
        run: |
          echo "========================================="
          echo "Snap Published Successfully!"
          echo "========================================="
          echo ""
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Channel: edge"
          echo ""
          echo "View at: https://snapcraft.io/sysmanage-agent-strict"
          echo ""
          echo "Install with:"
          echo "  sudo snap install sysmanage-agent-strict --edge"
          echo ""
          echo "To promote to other channels:"
          echo "  snapcraft release sysmanage-agent-strict <revision> beta"
          echo "  snapcraft release sysmanage-agent-strict <revision> candidate"
          echo "  snapcraft release sysmanage-agent-strict <revision> stable"
